site_name: Manuel d'Utilisation CLIMADA-CI
site_description: "Guide d'utilisation et de formation pour le modèle d'évaluation des risques climatiques CLIMADA."
site_url: https://nicaisekassi.github.io/Formation-CLIMADA-CI/
use_directory_urls: true

theme:
  name: readthedocs
  logo: assets/Picture.png
  prev_next_buttons_location: both

nav:
  - "Accueil": "index.md"
  - "Chapitre 1 - Installation": "chapitre1_installation.md"
  - "Chapitre 2 - Les Données d'Entrée": "chapitre2_donnees.md"
  - "Chapitre 3 - Travaux Pratiques": "chapitre3_tp.md"
  - "Chapitre 4 - Aide à la Décision": "chapitre4_decision.md"
  - "Chapitre 5 - Dépannage": "chapitre5_depannage.md"
  - "Conclusion": "conclusion_finale.md"
  - "Allez plus loin":
      - "Glossaire": "glossaire_complet.md"

extra_css:
  - assets/css/extra.css

extra_javascript:
  - auth/auth.js
